<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src'),
    'PhantomInstaller\\' => array($vendorDir . '/jakoch/phantomjs-installer/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'JonnyW\\PhantomJs\\' => array($vendorDir . '/josh/php-phantomjs/src'),
);
